### ISSUE TITLE
AWS getting started guide wrong order of commands

### ISSUE THREAD

**Issue by TjazVracko** [bifravst/bifravst#31]
I am trying toset up the AWS stack as per instructions here: [INSTRUCTIONS](https://bifravst.gitbook.io/bifravst/v/saga/bifravst-on-aws/gettingstarted)

I am able to get to the section titled "_Install Bifravst into your AWS account_" without issue.
In this section, the operations are as follows:
```
npx cdk bootstrap
npx cdk -a 'node dist/cdk/cloudformation-sourcecode.js' deploy
npx cdk deploy '*'
```

Running the first command (`npx cdk bootstrap`) gets the following error:
```
Error [ValidationError]: Stack with id bifravst-sourcecode does not exist
    at Request.extractError (/home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/comemaster/Documents/IRNAS/Nordic/bifravst-aws/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Stack with id bifravst-sourcecode does not exist',
  code: 'ValidationError',
  time: 2019-12-10T10:54:44.798Z,
  requestId: '9f651436-1cb9-4ddd-aae5-9d29c5b62f93',
  statusCode: 400,
  retryable: false,
  retryDelay: 2.069632182324943
}
Subprocess exited with error 1
```

Running the commands in a different order:
```
npx cdk -a 'node dist/cdk/cloudformation-sourcecode.js' deploy
npx cdk bootstrap
npx cdk deploy '*'
```
does not produce any errors (each ones gives a check mark). Issuing the commands like above I was able to continue and complete the whole guide/installation process and can access the online cat-tracker GUI as well as use the simulator to simulate cat activity. The system thus appears to be working.

I suggest switching the order of the commands in the guide, unless the cause of my error is related to something else?

**Comment by coderbyheart** [comment]
Yes, right, because the default cdk command tries to upload the lambdas to S3 here: 

https://github.com/bifravst/aws/blob/5dc6a3c27743960e0fde2219ef4bb8e0eba8faeb/cdk/cloudformation.ts#L12-L16

**Comment by coderbyheart** [comment]
Thanks for taking the time to report this issue, @comemaster!
